/** @type {import('jest').Config} */
module.exports = {
  collectCoverage: true,
  collectCoverageFrom: ['packages/**/*.{js,jsx,ts,tsx,vue}'],
  coveragePathIgnorePatterns: ['node_modules/', 'coverage/'],
  coverageReporters: ['lcov', 'text-summary'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^@polkadot/types/lookup$': '<rootDir>/packages/types/src/interfaces/types-lookup.ts',
    '^@sora-substrate/api$': '<rootDir>/packages/api/src',
    '^@sora-substrate/api/(.*)$': '<rootDir>/packages/api/src/$1',
    '^@sora-substrate/types$': '<rootDir>/packages/types/src',
    '^@sora-substrate/types/scripts/(.*)$': '<rootDir>/packages/types/scripts/$1',
    '^@sora-substrate/types/(.*)$': '<rootDir>/packages/types/src/$1',
    '^@sora-substrate/type-definitions$': '<rootDir>/packages/type-definitions/src',
    '^@sora-substrate/type-definitions/(.*)$': '<rootDir>/packages/type-definitions/src/$1',
    '^@sora-substrate/sdk$': '<rootDir>/packages/sdk/src',
    '^@sora-substrate/sdk/(.*)$': '<rootDir>/packages/sdk/src/$1',
    '^@sora-substrate/math$': '<rootDir>/packages/math/src',
    '^@sora-substrate/math/(.*)$': '<rootDir>/packages/math/src/$1',
    '^@sora-substrate/liquidity-proxy$': '<rootDir>/packages/liquidity-proxy/src',
    '^@sora-substrate/liquidity-proxy/(.*)$': '<rootDir>/packages/liquidity-proxy/src/$1',
    '^@sora-substrate/connection$': '<rootDir>/packages/connection/src',
    '^@sora-substrate/connection/(.*)$': '<rootDir>/packages/connection/src/$1',
  },
  modulePathIgnorePatterns: [
    '<rootDir>/build',
    '<rootDir>/packages/api/build',
    '<rootDir>/packages/math/build',
    '<rootDir>/packages/types/build',
    '<rootDir>/packages/type-definitions/build',
    '<rootDir>/packages/sdk/build',
    '<rootDir>/packages/liquidity-proxy/build',
    '<rootDir>/packages/connection/build',
  ],
  testEnvironment: 'node',
  testMatch: ['<rootDir>/tests/**/*.(spec|test).[tj]s'],
  transform: {
    '^.+\\.[tj]s$': ['babel-jest', { configFile: './babel.config.js' }],
  },
  transformIgnorePatterns: ['node_modules/(?!(?:@polkadot/util).*)'],
  verbose: true,
};
