module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  modulePathIgnorePatterns: [
    '<rootDir>/build',
    '<rootDir>/packages/api/build',
    '<rootDir>/packages/math/build',
    '<rootDir>/packages/types/build',
    '<rootDir>/packages/type-definitions/build',
    '<rootDir>/packages/sdk/build',
    '<rootDir>/packages/liquidity-proxy/build',
    '<rootDir>/packages/connection/build',
  ],
  verbose: true,
  transform: {
    '^.+\\.js$': 'babel-jest',
  },
  transformIgnorePatterns: ['node_modules/(?!(?:@polkadot/(?:util|types|types-codec|types-create))/)'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  resolver: '<rootDir>/jest.resolver.cjs',
  moduleNameMapper: {
    '^@sora-substrate/types/scripts/(.*)$': '<rootDir>/packages/types/scripts/$1',
    '^@sora-substrate/([a-z-]+)/src/(.*)$': '<rootDir>/packages/$1/src/$2',
    '^@sora-substrate/([a-z-]+)/scripts/(.*)$': '<rootDir>/packages/$1/scripts/$2',
    '^@sora-substrate/([a-z-]+)/?(.*)$': '<rootDir>/packages/$1/src/$2',
  },
  collectCoverage: true,
  collectCoverageFrom: ['packages/**/*.{js,jsx,ts,tsx,vue}'],
  coverageReporters: ['lcov'],
  coveragePathIgnorePatterns: ['node_modules/', 'coverage/'],
};
